apiVersion: v1
kind: ConfigMap
metadata:
  name: bish-app-config
  labels:
    app: bish-suite
    author: bishwayan
data:
  APP_ENV: "production"
  APP_PORT: "8080"
  LOG_LEVEL: "info"
  SERVICE_REGION: "ap-south-1"
  CONTACT_EMAIL: "bish@example.com"
