apiVersion: v1
kind: Secret
metadata:
  name: bish-app-secret
  labels:
    app: bish-suite
    author: bishwayan
type: Opaque
data:
  # Base64 for "bish_admin"
  DB_USERNAME: YmlzaF9hZG1pbg==
  # Base64 for "SecurePass2026!Bish"
  DB_PASSWORD: U2VjdXJlUGFzczIwMjYhQmlzaA==
  # Base64 for "api_key_bish_998811"
  API_SECRET_KEY: YXBpX2tleV9iaXNoXzk5ODgxMQ==
