apiVersion: v1
kind: Secret
metadata:
  name: bish-gateway-secrets
  labels:
    app: bish-gateway
    author: bishwayan
type: Opaque
data:
  # Base64 for "bish_db_master"
  DB_USER: YmlzaF9kYl9tYXN0ZXI=
  # Base64 for "ProdPass9988!Bish"
  DB_PASS: UHJvZFBhc3M5OTg4IUJpc2g=
  # Base64 for "jwt_token_key_bish_xyz"
  JWT_SECRET: And0X3Rva2VuX2tleV9iaXNoX3h5eg==
